# Generated by Django 3.1.6 on 2021-03-03 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0007_auto_20210210_1736'),
        ('insertion_order', '0011_auto_20210303_1800'),
        ('company_details', '0009_auto_20210210_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=120, unique=True)),
                ('total_amount', models.FloatField()),
                ('invoice_on', models.DateField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('campaigns', models.ManyToManyField(to='insertion_order.Campaigns')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.companydetails')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoice',
                'db_table': 'tbl_invoice',
            },
        ),
        migrations.CreateModel(
            name='ServiceCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('amount', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoices')),
            ],
            options={
                'verbose_name': 'Services Charge',
                'verbose_name_plural': 'Services Charges',
                'db_table': 'tbl_invoice_services_charges',
            },
        ),
        migrations.CreateModel(
            name='OtherCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('amount', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_charges', to='invoices.invoices')),
            ],
            options={
                'verbose_name': 'Other Charge',
                'verbose_name_plural': 'Other Charges',
                'db_table': 'tbl_invoice_other_charges',
            },
        ),
        migrations.CreateModel(
            name='BillingLineItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('start_date', models.DateField(verbose_name='Billing Start Date')),
                ('end_date', models.DateField(verbose_name='Billing End Date')),
                ('unit_cost', models.FloatField()),
                ('volume', models.IntegerField()),
                ('net_cost', models.FloatField()),
                ('ad_metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.metrics')),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.adsformats')),
                ('ethinicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.ethnicity')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoices')),
                ('io', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertion_order.insertionorders')),
            ],
            options={
                'verbose_name_plural': 'Line Items',
                'db_table': 'tbl_invoice_line_item',
                'unique_together': {('invoice', 'io', 'description')},
            },
        ),
    ]
