# Generated by Django 3.1.6 on 2021-03-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0010_auto_20210315_1313'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='contact_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company_details.companycontacts'),
            preserve_default=False,
        ),
    ]
