# Generated by Django 3.1.6 on 2021-03-16 16:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0013_auto_20210315_1313'),
        ('invoices', '0002_invoices_contact_person'),
    ]

    operations = [
    
        migrations.AddField(
            model_name='invoices',
            name='invoice_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoices',
            name='invoice_to',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoices',
            name='total_discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name='billinglineitems',
            unique_together={('invoice', 'line_item', 'description')},
        ),
        migrations.RemoveField(
            model_name='billinglineitems',
            name='io',
        ),
    ]
