# Generated by Django 3.1.6 on 2021-03-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20210316_1602'),
    ]

    operations = [
       
     
        migrations.DeleteModel(
            name='BillingLineItems',
        ),
    ]
