# Generated by Django 3.1.6 on 2021-03-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0013_auto_20210315_1313'),
        ('categories', '0007_auto_20210210_1736'),
        ('invoices', '0004_auto_20210316_1609'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='BillingLineItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('start_date', models.DateField(verbose_name='Billing Start Date')),
                ('end_date', models.DateField(verbose_name='Billing End Date')),
                ('unit_cost', models.FloatField()),
                ('volume', models.IntegerField()),
                ('net_cost', models.FloatField()),
                ('billing_cost', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
                ('ad_metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.metrics')),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.adsformats')),
                ('ethinicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.ethnicity')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoices')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertion_order.iodetails')),
            ],
            options={
                'verbose_name_plural': 'Line Items',
                'db_table': 'tbl_invoice_line_item',
                'unique_together': {('invoice', 'line_item', 'description')},
            },
        ),
    ]
