# Generated by Django 3.1.6 on 2021-03-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20210316_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='pdf_file',
        ),
    ]
