# Generated by Django 3.1.6 on 2021-03-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_remove_invoices_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='billing_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
