# Generated by Django 3.1.6 on 2021-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoices_billing_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
