# Generated by Django 3.1.6 on 2021-04-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_auto_20210316_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='additional_discount',
            field=models.PositiveIntegerField(default=0.0, verbose_name='Offers or Discount'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='total_discount',
            field=models.FloatField(default=0.0, verbose_name='Bill Adjustment'),
        ),
    ]
