# Generated by Django 3.1.6 on 2021-05-18 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_modeofpayment'),
        ('invoices', '0009_auto_20210421_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'All Invoice',
                'verbose_name_plural': '6. All Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoices',),
        ),
        migrations.CreateModel(
            name='FullyPaid',
            fields=[
            ],
            options={
                'verbose_name': 'Fully Paid',
                'verbose_name_plural': '5. Fully Paid Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoices',),
        ),
        migrations.CreateModel(
            name='NotPaid',
            fields=[
            ],
            options={
                'verbose_name': 'Not Paid',
                'verbose_name_plural': '1. Not Paid Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoices',),
        ),
        migrations.CreateModel(
            name='NotPaidOverDue',
            fields=[
            ],
            options={
                'verbose_name': 'Not Paid and Overdue',
                'verbose_name_plural': '2. Not Paid and Overdue Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoices',),
        ),
        migrations.CreateModel(
            name='PartiallyPaid',
            fields=[
            ],
            options={
                'verbose_name': 'Partially Paid',
                'verbose_name_plural': '3. Partially Paid Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoices',),
        ),
        migrations.CreateModel(
            name='PartiallyPaidOverDue',
            fields=[
            ],
            options={
                'verbose_name': 'Partially Paid and OverDue Invoices',
                'verbose_name_plural': '4. Partially Paid and OverDue Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoices',),
        ),
        migrations.AddField(
            model_name='invoices',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 18, 10, 25, 49, 480253)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoices',
            name='status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Partial Paid', 'Partial Paid'), ('Paid', 'Paid')], default='Not Paid', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(verbose_name='Transaction Date')),
                ('additional_info', models.CharField(blank=True, max_length=120, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='invoices.invoices')),
                ('mode_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.modeofpayment')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment History',
                'db_table': 'tbl_payment_history',
                'ordering': ('-created_on',),
            },
        ),
    ]
