# Generated by Django 3.1.6 on 2021-06-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20210518_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allinvoice',
            options={'verbose_name': 'All Invoice', 'verbose_name_plural': 'All Invoices'},
        ),
        migrations.AlterModelOptions(
            name='fullypaid',
            options={'verbose_name': 'Fully Paid', 'verbose_name_plural': 'Fully Paid Invoices'},
        ),
        migrations.AlterModelOptions(
            name='notpaid',
            options={'verbose_name': 'Not Paid', 'verbose_name_plural': 'Not Paid Invoices'},
        ),
        migrations.AlterModelOptions(
            name='notpaidoverdue',
            options={'verbose_name': 'Not Paid and Overdue', 'verbose_name_plural': 'Not Paid and Overdue Invoices'},
        ),
        migrations.AlterModelOptions(
            name='partiallypaid',
            options={'verbose_name': 'Partially Paid', 'verbose_name_plural': 'Partially Paid Invoices'},
        ),
        migrations.AlterModelOptions(
            name='partiallypaidoverdue',
            options={'verbose_name': 'Partially Paid and OverDue Invoices', 'verbose_name_plural': 'Partially Paid and OverDue Invoices'},
        ),
    ]
