# Generated by Django 3.1.6 on 2021-06-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_auto_20210609_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'Invoice & Payment',
                'verbose_name_plural': 'Invoice & Payment',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoices',),
        ),
    ]
