# Generated by Django 3.1.6 on 2021-06-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_clientinvoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientInvoice',
        ),
    ]
