# Generated by Django 3.1.6 on 2021-06-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_delete_clientinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='invoice_no',
            field=models.CharField(max_length=120, unique=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='invoice_on',
            field=models.DateField(verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Partial Paid', 'Partial Paid'), ('Paid', 'Paid')], default='Not Paid', max_length=20, verbose_name='Payment Status'),
        ),
    ]
