# Generated by Django 3.1.6 on 2021-07-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_auto_20210625_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
