# Generated by Django 3.1.6 on 2021-08-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_invoices_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Manager Approved'),
        ),
    ]
