# Generated by Django 3.1.6 on 2023-07-23 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_invoicebankdetails_invoicecompanyaddress'),
        ('invoices', '0016_auto_20210811_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='from_company_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.invoicecompanyaddress'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='from_company_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.invoicebankdetails'),
        ),
    ]
