# Generated by Django 3.1.6 on 2023-07-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_auto_20230723_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='gst',
            field=models.PositiveIntegerField(default=0.0, verbose_name='GST %'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='gst_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoices',
            name='vat_tax',
            field=models.PositiveIntegerField(default=0.0, verbose_name='VAT %'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='vat_tax_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
