# Generated by Django 3.1.6 on 2023-07-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_auto_20230723_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='gst',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='GST %'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='total_discount',
            field=models.FloatField(verbose_name='Bill Adjustment'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='vat_tax',
            field=models.PositiveIntegerField(blank=True, default=0.0, null=True, verbose_name='VAT %'),
        ),
    ]
