# Generated by Django 3.1.6 on 2023-07-24 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_auto_20230724_2046'),
        ('invoices', '0019_auto_20230723_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='authorized_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.invoiceauthorizedperson'),
        ),
    ]
