# Generated by Django 3.1.6 on 2023-08-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_invoices_authorized_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='total_discount',
            field=models.FloatField(default=0.0, verbose_name='Bill Adjustment'),
        ),
    ]
