# Generated by Django 3.1.6 on 2026-06-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0033_activecampaigns_completedcampaigns_inactivecampaigns'),
        ('invoices', '0021_auto_20230805_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partiallypaidoverdue',
            options={'verbose_name': 'Partially Paid and OverDue', 'verbose_name_plural': 'Partially Paid and OverDue Invoices'},
        ),
        migrations.AlterField(
            model_name='invoices',
            name='campaigns',
            field=models.ManyToManyField(related_name='invoiced_campaign', to='insertion_order.Campaigns'),
        ),
    ]
