# Generated by Django 3.1.6 on 2026-06-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_auto_20260606_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='invoice_month',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice Month'),
        ),
    ]
