# Generated by Django 3.1.6 on 2026-06-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_invoices_invoice_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='invoice_type',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='single', max_length=20),
        ),
    ]
