# Generated by Django 3.1.6 on 2026-06-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_invoices_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='additional_discount',
            field=models.FloatField(default=0.0, verbose_name='Offers or Discount'),
        ),
    ]
