# Generated by Django 3.1.6 on 2021-09-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insertion_order', '0028_campaigns_purchase_order_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItemUnderPacing',
            fields=[
            ],
            options={
                'verbose_name': 'Under Pacing Line Item',
                'verbose_name_plural': 'Over Pacing Line Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insertion_order.iodetails',),
        ),
    ]
