# Generated by Django 3.1.6 on 2021-07-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0026_auto_20210706_1718'),
        ('clientrequests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItemRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=256)),
                ('request_status', models.BooleanField(default=None, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertion_order.iodetails')),
            ],
            options={
                'verbose_name': 'Line Item Request',
                'verbose_name_plural': 'Line Item Request',
                'db_table': 'tbl_line_status_request',
            },
        ),
    ]
