# Generated by Django 3.1.6 on 2021-07-19 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0027_auto_20210719_1345'),
        ('clientrequests', '0002_lineitemrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrequest',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='lineitemrequest',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='lineitemrequest',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertion_order.iodetails', verbose_name='Line Item Name'),
        ),
        migrations.AlterField(
            model_name='lineitemrequest',
            name='status',
            field=models.CharField(max_length=30, verbose_name='Raise Status'),
        ),
        migrations.CreateModel(
            name='CampaignRequestImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaign-request')),
                ('campaign_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientrequests.campaignrequest')),
            ],
            options={
                'db_table': 'tbl_campaign_request_images',
            },
        ),
    ]
