# Generated by Django 3.1.6 on 2021-02-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_ethnicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='dail_code',
            field=models.IntegerField(default=91),
            preserve_default=False,
        ),
    ]
