# Generated by Django 3.1.6 on 2021-02-10 11:07

import categories.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_country_dail_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teams Details',
                'verbose_name_plural': 'Teams Details',
                'db_table': 'tbl_teams_details',
            },
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=categories.models.upload_to_title_images),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code_2',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code_3',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Currency Code'),
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.teams')),
            ],
            options={
                'verbose_name': 'Teams Role',
                'db_table': 'tbl_teams_role',
                'unique_together': {('team', 'title')},
            },
        ),
    ]
