# Generated by Django 3.1.6 on 2021-02-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20210210_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsformats',
            options={'verbose_name': 'Ad Format', 'verbose_name_plural': 'Ad Format'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AddField(
            model_name='teams',
            name='company',
            field=models.CharField(choices=[('Billiontags', 'Billiontags'), ('Client', 'Client')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='teams',
            unique_together={('title', 'company')},
        ),
    ]
