# Generated by Django 3.1.6 on 2021-02-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20210210_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teams',
            unique_together=set(),
        ),
    ]
