# Generated by Django 3.1.6 on 2021-02-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20210210_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='teams',
            unique_together={('title', 'company')},
        ),
    ]
