# Generated by Django 3.1.6 on 2021-05-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20210210_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeOfPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mode of Payment',
                'verbose_name_plural': 'Mode of Payment',
                'db_table': 'tbl_mode_of_payment',
            },
        ),
    ]
