# Generated by Django 3.1.6 on 2021-09-20 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_modeofpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTypeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Type Category',
                'verbose_name_plural': 'Media Type Categories',
                'db_table': 'tbl_media_type_category',
            },
        ),
        migrations.CreateModel(
            name='MediaTypeSuperCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Type Super Category',
                'verbose_name_plural': 'Media Type Super Categories',
                'db_table': 'tbl_media_type_super_category',
            },
        ),
        migrations.CreateModel(
            name='MediaTypeSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.mediatypecategory')),
            ],
            options={
                'verbose_name': 'Media Type Sub Category',
                'verbose_name_plural': 'Media Type Sub Categories',
                'db_table': 'tbl_media_type_sub_category',
            },
        ),
        migrations.AddField(
            model_name='mediatypecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.mediatypesupercategory'),
        ),
    ]
