# Generated by Django 3.1.6 on 2023-07-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_performancecategory_performancesubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=100, unique=True)),
                ('swift_code', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_invoice_bank_details',
            },
        ),
        migrations.CreateModel(
            name='InvoiceCompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=30)),
                ('gst_number', models.CharField(max_length=80)),
                ('cin_number', models.CharField(max_length=80)),
                ('tan_number', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_invoice_company_details',
            },
        ),
    ]
