# Generated by Django 3.1.6 on 2023-07-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_auto_20230723_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAuthorizedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('person_sign', models.ImageField(upload_to='authorized_person')),
                ('company_logo_sign', models.ImageField(upload_to='authorized_person_logo')),
            ],
        ),
        migrations.AlterField(
            model_name='invoicebankdetails',
            name='ifsc_code',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
