# Generated by Django 3.1.6 on 2023-07-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_auto_20230724_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceauthorizedperson',
            name='company_logo_sign',
            field=models.ImageField(upload_to='authorized_person_logo', verbose_name='Company Seal'),
        ),
        migrations.AlterField(
            model_name='invoiceauthorizedperson',
            name='person_sign',
            field=models.ImageField(upload_to='authorized_person', verbose_name='Person Sign'),
        ),
    ]
