# Generated by Django 3.1.6 on 2026-07-04 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_auto_20230724_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='AedExchangeRateMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.PositiveSmallIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AED Exchange Rate Month',
                'verbose_name_plural': 'AED Exchange Rate Months',
                'db_table': 'tbl_aed_exchange_rate_month',
                'ordering': ('year', 'month'),
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='AedExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('AUD', 'AUD'), ('CAD', 'CAD')], max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_date', models.DateField(help_text='CBUAE end-of-month date, eg: 2026-05-31')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='categories.aedexchangeratemonth')),
            ],
            options={
                'verbose_name': 'AED Exchange Rate',
                'verbose_name_plural': 'AED Exchange Rates',
                'db_table': 'tbl_aed_exchange_rate',
                'unique_together': {('month', 'currency')},
            },
        ),
    ]
