# Generated by Django 3.1.6 on 2026-07-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_aedexchangerate_aedexchangeratemonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'tbl_currency',
            },
        ),
        migrations.AlterField(
            model_name='aedexchangerate',
            name='effective_date',
            field=models.DateField(help_text='CBUAE last business day of month'),
        ),
        migrations.AlterField(
            model_name='aedexchangerate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.currency'),
        ),
    ]
