# Generated by Django 3.1.6 on 2026-07-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_auto_20260704_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aedexchangerate',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('AUD', 'AUD'), ('CAD', 'CAD')], max_length=3),
        ),
        migrations.AlterField(
            model_name='aedexchangerate',
            name='effective_date',
            field=models.DateField(help_text='CBUAE end-of-month date, eg: 2026-05-31'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
