# Generated by Django 3.1.6 on 2026-07-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0017_auto_20260704_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aedexchangerate',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('EUR', 'EUR'), ('NZD', 'NZD')], max_length=3),
        ),
    ]
