# Generated by Django 3.1.6 on 2021-02-08 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_ethnicity'),
        ('company_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertionOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=25, unique=True)),
                ('work_order_no', models.CharField(max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('Pre Payment', 'Pre Payment'), ('Post Payment', 'Post Payment')], max_length=50)),
                ('total_cost', models.FloatField()),
                ('total_impressions', models.FloatField()),
                ('io_file', models.FileField(blank=True, null=True, upload_to='')),
                ('signed_io_file', models.FileField(blank=True, null=True, upload_to='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.companydetails')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.paymentterms')),
            ],
            options={
                'verbose_name': 'Insertion Order',
                'verbose_name_plural': 'Insertion Orders',
                'db_table': 'tbl_insertion_order',
            },
        ),
        migrations.CreateModel(
            name='IODetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('unit_cost', models.FloatField()),
                ('volume', models.IntegerField()),
                ('ad_metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.metrics')),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.adsformats')),
                ('ethinicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.ethnicity')),
                ('io', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertion_order.insertionorders')),
            ],
            options={
                'db_table': 'tbl_io_details',
                'unique_together': {('io', 'description')},
            },
        ),
    ]
