# Generated by Django 3.1.6 on 2021-02-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0002_insertionorders_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='iodetails',
            name='net_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
