# Generated by Django 3.1.6 on 2021-02-08 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0003_iodetails_net_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insertionorders',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='insertionorders',
            name='total_impressions',
        ),
        migrations.AlterField(
            model_name='iodetails',
            name='io',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='io_details', to='insertion_order.insertionorders'),
        ),
    ]
