# Generated by Django 3.1.6 on 2021-02-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0005_auto_20210208_1049'),
        ('insertion_order', '0004_auto_20210208_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertionorders',
            name='contact_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company_details.companycontacts'),
            preserve_default=False,
        ),
    ]
