# Generated by Django 3.1.6 on 2021-02-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0005_insertionorders_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertionorders',
            name='name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
