# Generated by Django 3.1.6 on 2021-02-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0006_insertionorders_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iodetails',
            options={'verbose_name_plural': 'IO Details'},
        ),
        migrations.AlterField(
            model_name='insertionorders',
            name='order_id',
            field=models.CharField(max_length=25, unique=True, verbose_name='IO Number'),
        ),
        migrations.AlterField(
            model_name='insertionorders',
            name='work_order_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
