# Generated by Django 3.1.6 on 2021-02-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0007_auto_20210210_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertionorders',
            name='signed_io',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
