# Generated by Django 3.1.6 on 2021-02-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0008_insertionorders_signed_io'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertionorders',
            name='to_email',
            field=models.EmailField(default='jegatheeshwaran@billiontags.com', max_length=254),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmailCCContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_email', models.EmailField(max_length=254)),
                ('io', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertion_order.insertionorders')),
            ],
            options={
                'verbose_name': 'CC Email',
                'verbose_name_plural': 'CC Emails',
                'db_table': 'tbl_io_cc_details',
            },
        ),
    ]
