# Generated by Django 3.1.6 on 2021-02-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0009_auto_20210211_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertionorders',
            name='geo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
