# Generated by Django 3.1.6 on 2021-03-03 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20210210_1736'),
        ('company_details', '0009_auto_20210210_1620'),
        ('insertion_order', '0010_insertionorders_geo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iodetails',
            options={'verbose_name_plural': 'Line Items'},
        ),
        migrations.RemoveField(
            model_name='insertionorders',
            name='created_by',
        ),
        migrations.CreateModel(
            name='LineItemsReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_on', models.DateField()),
                ('impression', models.PositiveIntegerField()),
                ('clicks', models.PositiveIntegerField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='insertion_order.iodetails')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'tbl_line_items_reports',
            },
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Completed', 'Completed')], max_length=20)),
                ('payment_type', models.CharField(choices=[('Pre Payment', 'Pre Payment'), ('Post Payment', 'Post Payment')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.companydetails')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.paymentterms')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaign',
                'db_table': 'tbl_campaign',
            },
        ),
    ]
