# Generated by Django 3.1.6 on 2021-03-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0011_auto_20210303_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertionorders',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insertion_order', to='insertion_order.campaigns'),
            preserve_default=False,
        ),
    ]
