# Generated by Django 3.1.6 on 2021-03-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0012_insertionorders_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Pre Payment', 'Pre Payment'), ('Post Payment', 'Post Payment')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insertionorders',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Pre Payment', 'Pre Payment'), ('Post Payment', 'Post Payment')], max_length=50, null=True),
        ),
    ]
