# Generated by Django 3.1.6 on 2021-03-19 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insertion_order', '0013_auto_20210315_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineitemsreports',
            options={'ordering': ('report_on',), 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AddField(
            model_name='insertionorders',
            name='order_taken_by',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
