# Generated by Django 3.1.6 on 2021-05-17 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20210210_1736'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insertion_order', '0014_auto_20210319_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iodetails',
            options={'verbose_name': 'Booking Detail', 'verbose_name_plural': 'Booking Details'},
        ),
        migrations.RemoveField(
            model_name='insertionorders',
            name='company',
        ),
        migrations.RemoveField(
            model_name='insertionorders',
            name='signed_io_file',
        ),
        migrations.AlterField(
            model_name='insertionorders',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='IO Date'),
        ),
        migrations.AlterField(
            model_name='insertionorders',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Campaign Name'),
        ),
        migrations.AlterField(
            model_name='insertionorders',
            name='order_id',
            field=models.CharField(max_length=25, unique=True, verbose_name='Campaign ID'),
        ),
        migrations.AlterField(
            model_name='insertionorders',
            name='order_taken_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='insertionorders',
            name='signed_io',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Signed IO'),
        ),
        migrations.AlterField(
            model_name='insertionorders',
            name='work_order_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Client Campaign ID'),
        ),
        migrations.AlterField(
            model_name='iodetails',
            name='ad_metrics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.metrics', verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='iodetails',
            name='ad_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.adsformats', verbose_name='Ad Format'),
        ),
        migrations.AlterField(
            model_name='iodetails',
            name='description',
            field=models.CharField(max_length=120, verbose_name='Line Item Name'),
        ),
    ]
