# Generated by Django 3.1.6 on 2021-05-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0015_auto_20210517_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCampaigns',
            fields=[
            ],
            options={
                'verbose_name': 'Active Campaigns',
                'verbose_name_plural': '1. Active Campaigns',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insertion_order.campaigns',),
        ),
        migrations.CreateModel(
            name='CompletedCampaigns',
            fields=[
            ],
            options={
                'verbose_name': 'Completed Campaigns',
                'verbose_name_plural': '3. Completed Campaigns',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insertion_order.campaigns',),
        ),
        migrations.CreateModel(
            name='InactiveCampaigns',
            fields=[
            ],
            options={
                'verbose_name': 'Paused Campaigns',
                'verbose_name_plural': '2. Paused Campaigns',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insertion_order.campaigns',),
        ),
        migrations.CreateModel(
            name='LineItems',
            fields=[
            ],
            options={
                'verbose_name': 'Line Items',
                'verbose_name_plural': '4. Line Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insertion_order.iodetails',),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='brand',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='subagency',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='work_order_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Client Campaign ID'),
        ),
        migrations.AddField(
            model_name='iodetails',
            name='item_id',
            field=models.CharField(default='LI', max_length=60, verbose_name='Line Item ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='campaign_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Campaign ID'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Campaign Name'),
        ),
        migrations.AlterField(
            model_name='insertionorders',
            name='name',
            field=models.CharField(max_length=120, verbose_name='IO Name'),
        ),
        migrations.AlterField(
            model_name='insertionorders',
            name='order_id',
            field=models.CharField(max_length=25, unique=True, verbose_name='IO ID'),
        ),
    ]
