# Generated by Django 3.1.6 on 2021-05-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0016_auto_20210525_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iodetails',
            options={'ordering': ('id',), 'verbose_name': 'Booking Detail', 'verbose_name_plural': 'Booking Details'},
        ),
        migrations.AddField(
            model_name='lineitemsreports',
            name='budget',
            field=models.FloatField(default=0.0),
        ),
    ]
