# Generated by Django 3.1.6 on 2021-06-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0017_auto_20210527_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='report_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Reporting ID'),
        ),
        migrations.AddField(
            model_name='insertionorders',
            name='report_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Reporting ID'),
        ),
        migrations.AddField(
            model_name='iodetails',
            name='report_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Reporting ID'),
        ),
    ]
