# Generated by Django 3.1.6 on 2021-06-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0018_auto_20210609_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitemsreports',
            name='media_cost',
            field=models.FloatField(default=0.0, verbose_name='Media Cost (Advertiser Currency)'),
        ),
        migrations.AlterField(
            model_name='lineitemsreports',
            name='budget',
            field=models.FloatField(default=0.0, verbose_name='Revenue (Adv Currency)'),
        ),
    ]
