# Generated by Django 3.1.6 on 2021-06-17 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0019_auto_20210609_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertionorders',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insertion_order', to='insertion_order.campaigns'),
        ),
        migrations.CreateModel(
            name='SubCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=20, unique=True)),
                ('report_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='Reporting ID')),
                ('name', models.CharField(max_length=120, verbose_name='Campaign Name')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_campaign', to='insertion_order.campaigns')),
            ],
            options={
                'verbose_name': 'Sub Campaign',
                'verbose_name_plural': 'Sub Campaigns',
                'db_table': 'tbl_sub_campaigns',
            },
        ),
       
    ]
