# Generated by Django 3.1.6 on 2021-06-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0020_auto_20210617_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertionorders',
            name='sub_campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insertion_order', to='insertion_order.subcampaign'),
            preserve_default=False,
        ),
    ]
