# Generated by Django 3.1.6 on 2021-06-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0013_companydetails_user'),
        ('insertion_order', '0021_insertionorders_sub_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.companydetails', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='status',
            field=models.CharField(choices=[('Active', 'Scheduled'), ('Live', 'Live'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Stop', 'Stop')], max_length=20),
        ),
        migrations.AlterField(
            model_name='insertionorders',
            name='to_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='subcampaign',
            name='booking_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Sub Campaign ID'),
        ),
        migrations.AlterField(
            model_name='subcampaign',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Sub Campaign Name'),
        ),
    ]
