# Generated by Django 3.1.6 on 2021-06-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0022_auto_20210622_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcampaign',
            name='status',
            field=models.CharField(choices=[('Active', 'Scheduled'), ('Live', 'Live'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Stopped', 'Stopped')], default='Live', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='status',
            field=models.CharField(choices=[('Active', 'Scheduled'), ('Live', 'Live'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Stopped', 'Stopped')], max_length=20),
        ),
    ]
