# Generated by Django 3.1.6 on 2021-06-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0023_auto_20210623_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='iodetails',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Stopped', 'Stopped')], default='Live', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Stopped', 'Stopped')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subcampaign',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Stopped', 'Stopped')], max_length=20),
        ),
    ]
