# Generated by Django 3.1.6 on 2021-06-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0024_auto_20210623_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='end_date',
            field=models.DateField(verbose_name='Campaign End Date'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='start_date',
            field=models.DateField(verbose_name='Campaign Start Date'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Stopped', 'Stopped')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='subcampaign',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='subcampaign',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='subcampaign',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Stopped', 'Stopped')], max_length=20, verbose_name='Status'),
        ),
    ]
