# Generated by Django 3.1.6 on 2021-07-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0025_auto_20210624_1942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveCampaigns',
        ),
        migrations.DeleteModel(
            name='CompletedCampaigns',
        ),
        migrations.DeleteModel(
            name='InactiveCampaigns',
        ),
        migrations.AddField(
            model_name='insertionorders',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Stopped', 'Stopped')], default='Live', max_length=20, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iodetails',
            name='avg_ctr',
            field=models.FloatField(default=3, verbose_name='Average CTR'),
            preserve_default=False,
        ),
    ]
