# Generated by Django 3.1.6 on 2021-07-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0026_auto_20210706_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcampaign',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_campaign', to='insertion_order.campaigns', verbose_name='Campaign Name'),
        ),
        migrations.AlterField(
            model_name='subcampaign',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Stopped', 'Stopped')], max_length=20, verbose_name='Sub Campaign Status'),
        ),
    ]
