# Generated by Django 3.1.6 on 2021-08-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0027_auto_20210719_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='purchase_order_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Purchase Order ID'),
        ),
    ]
