# Generated by Django 3.1.6 on 2021-09-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0028_campaigns_purchase_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitemsreports',
            name='measurable_impression',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lineitemsreports',
            name='video_end',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lineitemsreports',
            name='video_start',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lineitemsreports',
            name='viewable_impression',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
