# Generated by Django 3.1.6 on 2021-09-20 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_auto_20210920_1747'),
        ('insertion_order', '0029_auto_20210920_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='iodetails',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.mediatypesubcategory'),
        ),
    ]
