# Generated by Django 3.1.6 on 2021-09-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0030_iodetails_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitemsreports',
            name='fist_quartile_view',
            field=models.PositiveIntegerField(default=0, verbose_name='1st Quartile Views'),
        ),
        migrations.AddField(
            model_name='lineitemsreports',
            name='second_quartile_view',
            field=models.PositiveIntegerField(default=0, verbose_name='Midpoint Views'),
        ),
        migrations.AddField(
            model_name='lineitemsreports',
            name='third_quartile_view',
            field=models.PositiveIntegerField(default=0, verbose_name='3rd Quartile Views'),
        ),
    ]
