# Generated by Django 3.1.6 on 2021-10-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_performancecategory_performancesubcategory'),
        ('insertion_order', '0031_auto_20210923_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItemReportingID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=60, verbose_name='Reporting ID')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_ids', to='insertion_order.iodetails')),
            ],
            options={
                'verbose_name': 'Line Items Report',
                'verbose_name_plural': 'Line Items Report',
                'db_table': 'tbl_line_item_reports_id',
            },
        ),
        migrations.CreateModel(
            name='ReportingIdReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_on', models.DateField()),
                ('impression', models.PositiveIntegerField()),
                ('clicks', models.PositiveIntegerField()),
                ('viewable_impression', models.PositiveIntegerField(default=0)),
                ('measurable_impression', models.PositiveIntegerField(default=0)),
                ('video_start', models.PositiveIntegerField(default=0)),
                ('video_end', models.PositiveIntegerField(default=0)),
                ('fist_quartile_view', models.PositiveIntegerField(default=0, verbose_name='1st Quartile Views')),
                ('second_quartile_view', models.PositiveIntegerField(default=0, verbose_name='Midpoint Views')),
                ('third_quartile_view', models.PositiveIntegerField(default=0, verbose_name='3rd Quartile Views')),
                ('budget', models.FloatField(default=0.0, verbose_name='Revenue (Adv Currency)')),
                ('media_cost', models.FloatField(default=0.0, verbose_name='Media Cost (Advertiser Currency)')),
                ('reporting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting', to='insertion_order.lineitemreportingid')),
            ],
            options={
                'verbose_name': 'ReportId Report',
                'verbose_name_plural': 'ReportId Reports',
                'db_table': 'tbl_line_items_report_id_reports',
                'ordering': ('report_on',),
            },
        ),
        migrations.CreateModel(
            name='LineItemsPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('base_value', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='categories.performancesubcategory')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_performance', to='insertion_order.iodetails')),
            ],
            options={
                'verbose_name': 'Line Item',
                'db_table': 'tbl_line_item_performance',
            },
        ),
    ]
