# Generated by Django 3.1.6 on 2026-06-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_order', '0032_lineitemreportingid_lineitemsperformance_reportingidreports'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCampaigns',
            fields=[
            ],
            options={
                'verbose_name': 'Live Campaign',
                'verbose_name_plural': '1. Live Campaigns',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insertion_order.campaigns',),
        ),
        migrations.CreateModel(
            name='CompletedCampaigns',
            fields=[
            ],
            options={
                'verbose_name': 'Completed Campaign',
                'verbose_name_plural': '3. Completed Campaigns',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insertion_order.campaigns',),
        ),
        migrations.CreateModel(
            name='InactiveCampaigns',
            fields=[
            ],
            options={
                'verbose_name': 'Upcoming Campaign',
                'verbose_name_plural': '2. Upcoming Campaigns',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insertion_order.campaigns',),
        ),
    ]
