# Generated by Django 3.1.6 on 2021-02-05 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('gst_no', models.CharField(blank=True, max_length=40, null=True)),
                ('cin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_country', to='categories.country')),
            ],
            options={
                'verbose_name': 'Company Details',
                'verbose_name_plural': 'Company Details',
                'db_table': 'tbl_company_details',
            },
        ),
        migrations.CreateModel(
            name='CompanyUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_signature', models.ImageField(upload_to='company-user-signature')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.companydetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Uer',
                'verbose_name_plural': 'Company Users',
                'db_table': 'tbl_company_users',
            },
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('zipcode', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('billing_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_currency', to='categories.country')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.companydetails')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.country')),
            ],
            options={
                'verbose_name': 'Company Address',
                'verbose_name_plural': 'Company Address',
                'db_table': 'tbl_company_address',
            },
        ),
    ]
