# Generated by Django 3.1.6 on 2021-02-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='is_domestic',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
