# Generated by Django 3.1.6 on 2026-07-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='show_campaign_name_in_email',
            field=models.BooleanField(default=False, verbose_name='Campaign name display in the email'),
        ),
    ]
