# Generated by Django 3.1.6 on 2021-02-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0002_companydetails_is_domestic'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='email',
            field=models.EmailField(default='jack@billiontags.com', max_length=254),
            preserve_default=False,
        ),
    ]
