# Generated by Django 3.1.6 on 2021-02-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0003_companydetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='address_line_1',
            field=models.CharField(default='2323', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetails',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
