# Generated by Django 3.1.6 on 2021-02-08 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_country_dail_code'),
        ('company_details', '0004_auto_20210208_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('destination', models.CharField(max_length=120)),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('zipcode', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('billing_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_currency', to='categories.country')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.companydetails')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.country')),
            ],
            options={
                'verbose_name': 'Company Contacts',
                'verbose_name_plural': 'Company Contacts',
                'db_table': 'tbl_company_contacts',
            },
        ),
        migrations.DeleteModel(
            name='CompanyAddress',
        ),
    ]
