# Generated by Django 3.1.6 on 2021-02-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20210210_1107'),
        ('company_details', '0005_auto_20210208_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyusers',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.roles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyusers',
            name='digital_signature',
            field=models.ImageField(blank=True, null=True, upload_to='company-user-signature'),
        ),
    ]
