# Generated by Django 3.1.6 on 2021-02-10 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20210210_1609'),
        ('company_details', '0006_auto_20210210_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('zipcode', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Address',
                'verbose_name_plural': 'Company Address',
                'db_table': 'tbl_company_address',
            },
        ),
        migrations.RemoveField(
            model_name='companycontacts',
            name='billing_currency',
        ),
        migrations.AddField(
            model_name='companycontacts',
            name='digital_signature',
            field=models.ImageField(blank=True, null=True, upload_to='company-user-signature'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='billing_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='billing_currency', to='categories.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetails',
            name='zipcode',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companycontacts',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.roles', verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='companycontacts',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='companycontacts',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='CompanyUsers',
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.companydetails'),
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.country'),
        ),
    ]
