# Generated by Django 3.1.6 on 2021-02-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0007_auto_20210210_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontacts',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
