# Generated by Django 3.1.6 on 2021-02-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0008_auto_20210210_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontacts',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
