# Generated by Django 3.1.6 on 2021-03-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20210210_1736'),
        ('company_details', '0009_auto_20210210_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.paymentterms'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='payment_type',
            field=models.CharField(choices=[('Pre Payment', 'Pre Payment'), ('Post Payment', 'Post Payment')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
