# Generated by Django 3.1.6 on 2021-05-25 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0010_auto_20210315_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='client_id',
            field=models.CharField(default='CL', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetails',
            name='wallet_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Wallet Available Amount'),
        ),
        migrations.CreateModel(
            name='CompanyWalletHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('is_credit', models.BooleanField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_history', to='company_details.companydetails')),
            ],
            options={
                'verbose_name': 'Wallet History',
                'verbose_name_plural': 'Wallet History',
                'db_table': 'tbl_company_wallet_history',
            },
        ),
    ]
