# Generated by Django 3.1.6 on 2021-06-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0011_auto_20210525_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydetails',
            options={'ordering': ['-client_id'], 'verbose_name': 'Company Details', 'verbose_name_plural': 'Company Details'},
        ),
        migrations.AddField(
            model_name='companydetails',
            name='report_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Reporting ID'),
        ),
    ]
