# Generated by Django 3.1.6 on 2021-10-25 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_details', '0014_auto_20210709_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontacts',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_contact_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
