# Generated by Django 3.1.6 on 2026-06-20 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_auto_20230724_2046'),
        ('company_details', '0015_companycontacts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='default_authorized_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.invoiceauthorizedperson'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='default_contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_invoice_contact', to='company_details.companycontacts'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='default_invoice_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.invoicecompanyaddress'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='default_invoice_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.invoicebankdetails'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='invoice_type',
            field=models.CharField(choices=[('single', 'Single Invoice'), ('multiple', 'Multiple Invoice')], default='single', max_length=20),
        ),
    ]
