# Generated by Django 3.1.6 on 2026-06-22 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_auto_20230724_2046'),
        ('company_details', '0016_auto_20260620_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='default_authorized_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.invoiceauthorizedperson', verbose_name='Authorized person'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='default_contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_invoice_contact', to='company_details.companycontacts', verbose_name='Contact person'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='default_invoice_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.invoicecompanyaddress', verbose_name='From company address'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='default_invoice_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.invoicebankdetails', verbose_name='From bank account'),
        ),
    ]
