# Generated by Django 3.1.6 on 2026-07-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0017_auto_20260622_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='enable_aed_invoice',
            field=models.BooleanField(default=False, help_text="If checked, an additional 'View AED Invoice' PDF option will be shown for this company's invoices.", verbose_name='Enable AED Invoice'),
        ),
    ]
